DELETE FROM llm_call WHERE id LIKE 'demo-call-%';

INSERT OR REPLACE INTO provider_config (
  id,
  provider,
  display_name,
  base_url,
  api_key_ref,
  is_default,
  created_at,
  updated_at
) VALUES (
  'demo-openai-compatible',
  'openai-compatible',
  'Demo OpenAI Compatible',
  'https://api.openai.com',
  NULL,
  1,
  datetime('now', 'localtime'),
  datetime('now', 'localtime')
);

INSERT OR REPLACE INTO pricing_rule (
  id,
  provider,
  model,
  input_usd_per_1m,
  cached_input_usd_per_1m,
  output_usd_per_1m,
  reasoning_output_usd_per_1m,
  effective_from,
  effective_to,
  source,
  created_at,
  updated_at
) VALUES
  (
    'demo-pricing-gpt-5-mini',
    'openai-compatible',
    'gpt-5-mini',
    0.25,
    0.025,
    2.00,
    NULL,
    '2026-01-01',
    NULL,
    'demo',
    datetime('now', 'localtime'),
    datetime('now', 'localtime')
  ),
  (
    'demo-pricing-gpt-4-1-mini',
    'openai-compatible',
    'gpt-4.1-mini',
    0.40,
    0.10,
    1.60,
    NULL,
    '2026-01-01',
    NULL,
    'demo',
    datetime('now', 'localtime'),
    datetime('now', 'localtime')
  );

INSERT OR REPLACE INTO llm_call (
  id,
  started_at,
  ended_at,
  date_local,
  provider,
  provider_config_id,
  api_type,
  model_requested,
  model_response,
  agent_id,
  agent_name,
  agent_run_id,
  workflow_id,
  workflow_step,
  session_id,
  trace_id,
  span_id,
  parent_span_id,
  project_id,
  user_id,
  environment,
  feature,
  input_tokens,
  output_tokens,
  cached_input_tokens,
  cache_write_input_tokens,
  reasoning_output_tokens,
  audio_input_tokens,
  audio_output_tokens,
  image_input_tokens,
  image_output_tokens,
  total_tokens,
  total_billable_tokens,
  request_count,
  tool_call_count,
  retry_count,
  latency_ms,
  http_status,
  status,
  error_type,
  error_message,
  estimated_cost_usd,
  provider_reported_cost_usd,
  reconciled_cost_usd,
  cost_source,
  usage_source,
  raw_usage_json,
  raw_response_json,
  request_hash,
  response_hash,
  prompt_template_id,
  created_at
) VALUES
  (
    'demo-call-today-researcher-1',
    datetime('now', 'localtime', '-90 minutes'),
    datetime('now', 'localtime', '-89 minutes'),
    date('now', 'localtime'),
    'openai-compatible',
    'demo-openai-compatible',
    'chat_completions',
    'gpt-5-mini',
    'gpt-5-mini',
    'researcher',
    'Research Agent',
    'run_demo_001',
    'report_generation',
    'summarize_sources',
    'sess_demo_001',
    'trace_demo_001',
    'span_demo_001',
    NULL,
    'demo_project',
    'local_user',
    'dev',
    'daily_report',
    6200,
    2200,
    1800,
    0,
    320,
    0,
    0,
    0,
    0,
    8400,
    6600,
    1,
    2,
    0,
    1180,
    200,
    'success',
    NULL,
    NULL,
    0.021,
    NULL,
    NULL,
    'demo_seed',
    'provider_response',
    '{"prompt_tokens":6200,"completion_tokens":2200,"total_tokens":8400,"prompt_tokens_details":{"cached_tokens":1800},"completion_tokens_details":{"reasoning_tokens":320}}',
    NULL,
    'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
    'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb',
    NULL,
    datetime('now', 'localtime')
  ),
  (
    'demo-call-today-researcher-2',
    datetime('now', 'localtime', '-55 minutes'),
    datetime('now', 'localtime', '-54 minutes'),
    date('now', 'localtime'),
    'openai-compatible',
    'demo-openai-compatible',
    'responses',
    'gpt-5-mini',
    'gpt-5-mini',
    'researcher',
    'Research Agent',
    'run_demo_002',
    'report_generation',
    'draft_findings',
    'sess_demo_001',
    'trace_demo_002',
    'span_demo_002',
    NULL,
    'demo_project',
    'local_user',
    'dev',
    'daily_report',
    4800,
    1720,
    1600,
    0,
    260,
    0,
    0,
    0,
    0,
    6520,
    4920,
    1,
    1,
    0,
    940,
    200,
    'success',
    NULL,
    NULL,
    0.016,
    NULL,
    NULL,
    'demo_seed',
    'provider_response',
    '{"input_tokens":4800,"output_tokens":1720,"total_tokens":6520,"input_tokens_details":{"cached_tokens":1600},"output_tokens_details":{"reasoning_tokens":260}}',
    NULL,
    'cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc',
    'dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd',
    NULL,
    datetime('now', 'localtime')
  ),
  (
    'demo-call-today-analyst-error',
    datetime('now', 'localtime', '-18 minutes'),
    datetime('now', 'localtime', '-17 minutes'),
    date('now', 'localtime'),
    'openai-compatible',
    'demo-openai-compatible',
    'chat_completions',
    'gpt-5-mini',
    'gpt-5-mini',
    'analyst',
    'Analysis Agent',
    'run_demo_003',
    'literature_scan',
    'rank_sources',
    'sess_demo_002',
    'trace_demo_003',
    'span_demo_003',
    NULL,
    'demo_project',
    'local_user',
    'dev',
    'source_review',
    2200,
    800,
    800,
    0,
    100,
    0,
    0,
    0,
    0,
    3000,
    2200,
    1,
    0,
    1,
    1500,
    429,
    'error',
    'rate_limit',
    'provider returned rate limit',
    0.008,
    NULL,
    NULL,
    'demo_seed',
    'provider_response',
    '{"prompt_tokens":2200,"completion_tokens":800,"total_tokens":3000,"prompt_tokens_details":{"cached_tokens":800},"completion_tokens_details":{"reasoning_tokens":100}}',
    NULL,
    'eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
    'ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff',
    NULL,
    datetime('now', 'localtime')
  ),
  (
    'demo-call-yesterday-coder',
    datetime('now', 'localtime', '-1 day', '-70 minutes'),
    datetime('now', 'localtime', '-1 day', '-69 minutes'),
    date('now', 'localtime', '-1 day'),
    'openai-compatible',
    'demo-openai-compatible',
    'chat_completions',
    'gpt-4.1-mini',
    'gpt-4.1-mini',
    'coder',
    'Coding Agent',
    'run_demo_004',
    'code_review',
    'review_patch',
    'sess_demo_003',
    'trace_demo_004',
    'span_demo_004',
    NULL,
    'demo_project',
    'local_user',
    'dev',
    'review',
    8500,
    3500,
    1200,
    0,
    240,
    0,
    0,
    0,
    0,
    12000,
    10800,
    1,
    3,
    0,
    1320,
    200,
    'success',
    NULL,
    NULL,
    0.026,
    NULL,
    NULL,
    'demo_seed',
    'provider_response',
    '{"prompt_tokens":8500,"completion_tokens":3500,"total_tokens":12000,"prompt_tokens_details":{"cached_tokens":1200},"completion_tokens_details":{"reasoning_tokens":240}}',
    NULL,
    '1111111111111111111111111111111111111111111111111111111111111111',
    '2222222222222222222222222222222222222222222222222222222222222222',
    NULL,
    datetime('now', 'localtime')
  ),
  (
    'demo-call-two-days-researcher',
    datetime('now', 'localtime', '-2 days', '-45 minutes'),
    datetime('now', 'localtime', '-2 days', '-44 minutes'),
    date('now', 'localtime', '-2 days'),
    'openai-compatible',
    'demo-openai-compatible',
    'responses',
    'gpt-5-mini',
    'gpt-5-mini',
    'researcher',
    'Research Agent',
    'run_demo_005',
    'report_generation',
    'outline_report',
    'sess_demo_004',
    'trace_demo_005',
    'span_demo_005',
    NULL,
    'demo_project',
    'local_user',
    'dev',
    'daily_report',
    7600,
    2900,
    2400,
    0,
    380,
    0,
    0,
    0,
    0,
    10500,
    8100,
    1,
    2,
    0,
    1010,
    200,
    'success',
    NULL,
    NULL,
    0.022,
    NULL,
    NULL,
    'demo_seed',
    'provider_response',
    '{"input_tokens":7600,"output_tokens":2900,"total_tokens":10500,"input_tokens_details":{"cached_tokens":2400},"output_tokens_details":{"reasoning_tokens":380}}',
    NULL,
    '3333333333333333333333333333333333333333333333333333333333333333',
    '4444444444444444444444444444444444444444444444444444444444444444',
    NULL,
    datetime('now', 'localtime')
  );
